/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Entry {
  'ratio_bonus' : bigint,
  'tasks' : Tasks,
  'screen_time' : bigint,
  'note' : string,
  'deep_work_done' : boolean,
  'screen_penalty' : bigint,
  'final_score' : bigint,
  'task_score' : bigint,
  'productive_time' : bigint,
  'reflection' : string,
  'ratio' : number,
}
export interface EntryWithDate { 'date' : string, 'entry' : Entry }
export interface ReflectionData {
  'sleep_hours' : number,
  'energy_level' : bigint,
  'distraction_tags' : Array<string>,
}
export interface ReflectionWithDate { 'data' : ReflectionData, 'date' : string }
export interface Settings { 'streak_threshold' : bigint }
export interface StreakData {
  'longest_streak' : bigint,
  'current_streak' : bigint,
  'last_reset_date' : [] | [string],
}
export type Tasks = Array<[string, boolean]>;
export interface _SERVICE {
  'clearAllEntries' : ActorMethod<[], undefined>,
  'clearAllReflectionData' : ActorMethod<[], undefined>,
  'getAllEntries' : ActorMethod<[], Array<EntryWithDate>>,
  'getAllReflectionDates' : ActorMethod<[], Array<string>>,
  'getAllReflections' : ActorMethod<[], Array<ReflectionWithDate>>,
  'getEntry' : ActorMethod<[string], [] | [Entry]>,
  'getReflection' : ActorMethod<[string], [] | [ReflectionData]>,
  'getSettings' : ActorMethod<[], Settings>,
  'getStreakData' : ActorMethod<[], StreakData>,
  'saveEntry' : ActorMethod<[string, Entry], undefined>,
  'saveReflection' : ActorMethod<[string, ReflectionData], undefined>,
  'saveSettings' : ActorMethod<[Settings], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];