/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Tasks = IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool));
export const Entry = IDL.Record({
  'ratio_bonus' : IDL.Nat,
  'tasks' : Tasks,
  'screen_time' : IDL.Nat,
  'note' : IDL.Text,
  'deep_work_done' : IDL.Bool,
  'screen_penalty' : IDL.Nat,
  'final_score' : IDL.Int,
  'task_score' : IDL.Nat,
  'productive_time' : IDL.Nat,
  'reflection' : IDL.Text,
  'ratio' : IDL.Float64,
});
export const EntryWithDate = IDL.Record({ 'date' : IDL.Text, 'entry' : Entry });
export const ReflectionData = IDL.Record({
  'sleep_hours' : IDL.Float64,
  'energy_level' : IDL.Nat,
  'distraction_tags' : IDL.Vec(IDL.Text),
});
export const ReflectionWithDate = IDL.Record({
  'data' : ReflectionData,
  'date' : IDL.Text,
});
export const Settings = IDL.Record({ 'streak_threshold' : IDL.Nat });
export const StreakData = IDL.Record({
  'longest_streak' : IDL.Nat,
  'current_streak' : IDL.Nat,
  'last_reset_date' : IDL.Opt(IDL.Text),
});
export const DailyMetrics = IDL.Record({
  'energy_level' : IDL.Nat,
  'sleep_hours' : IDL.Float64,
  'focus_quality' : IDL.Nat,
  'mental_clarity' : IDL.Nat,
  'motivation_level' : IDL.Nat,
  'day_rating' : IDL.Nat,
});

export const idlService = IDL.Service({
  'clearAllEntries' : IDL.Func([], [], []),
  'clearAllReflectionData' : IDL.Func([], [], []),
  'getAllEntries' : IDL.Func([], [IDL.Vec(EntryWithDate)], ['query']),
  'getAllReflectionDates' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
  'getAllReflections' : IDL.Func([], [IDL.Vec(ReflectionWithDate)], ['query']),
  'getEntry' : IDL.Func([IDL.Text], [IDL.Opt(Entry)], ['query']),
  'getReflection' : IDL.Func([IDL.Text], [IDL.Opt(ReflectionData)], ['query']),
  'getDailyMetrics' : IDL.Func([IDL.Text], [IDL.Opt(DailyMetrics)], ['query']),
  'getSettings' : IDL.Func([], [Settings], ['query']),
  'getStreakData' : IDL.Func([], [StreakData], ['query']),
  'saveEntry' : IDL.Func([IDL.Text, Entry], [], []),
  'saveReflection' : IDL.Func([IDL.Text, ReflectionData], [], []),
  'saveDailyMetrics' : IDL.Func([IDL.Text, DailyMetrics], [], []),
  'saveSettings' : IDL.Func([Settings], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Tasks = IDL.Vec(IDL.Tuple(IDL.Text, IDL.Bool));
  const Entry = IDL.Record({
    'ratio_bonus' : IDL.Nat,
    'tasks' : Tasks,
    'screen_time' : IDL.Nat,
    'note' : IDL.Text,
    'deep_work_done' : IDL.Bool,
    'screen_penalty' : IDL.Nat,
    'final_score' : IDL.Int,
    'task_score' : IDL.Nat,
    'productive_time' : IDL.Nat,
    'reflection' : IDL.Text,
    'ratio' : IDL.Float64,
  });
  const EntryWithDate = IDL.Record({ 'date' : IDL.Text, 'entry' : Entry });
  const ReflectionData = IDL.Record({
    'sleep_hours' : IDL.Float64,
    'energy_level' : IDL.Nat,
    'distraction_tags' : IDL.Vec(IDL.Text),
  });
  const ReflectionWithDate = IDL.Record({
    'data' : ReflectionData,
    'date' : IDL.Text,
  });
  const Settings = IDL.Record({ 'streak_threshold' : IDL.Nat });
  const StreakData = IDL.Record({
    'longest_streak' : IDL.Nat,
    'current_streak' : IDL.Nat,
    'last_reset_date' : IDL.Opt(IDL.Text),
  });
  const DailyMetrics = IDL.Record({
    'energy_level' : IDL.Nat,
    'sleep_hours' : IDL.Float64,
    'focus_quality' : IDL.Nat,
    'mental_clarity' : IDL.Nat,
    'motivation_level' : IDL.Nat,
    'day_rating' : IDL.Nat,
  });
  
  return IDL.Service({
    'clearAllEntries' : IDL.Func([], [], []),
    'clearAllReflectionData' : IDL.Func([], [], []),
    'getAllEntries' : IDL.Func([], [IDL.Vec(EntryWithDate)], ['query']),
    'getAllReflectionDates' : IDL.Func([], [IDL.Vec(IDL.Text)], []),
    'getAllReflections' : IDL.Func([], [IDL.Vec(ReflectionWithDate)], ['query']),
    'getEntry' : IDL.Func([IDL.Text], [IDL.Opt(Entry)], ['query']),
    'getReflection' : IDL.Func([IDL.Text], [IDL.Opt(ReflectionData)], ['query']),
    'getDailyMetrics' : IDL.Func([IDL.Text], [IDL.Opt(DailyMetrics)], ['query']),
    'getSettings' : IDL.Func([], [Settings], ['query']),
    'getStreakData' : IDL.Func([], [StreakData], ['query']),
    'saveEntry' : IDL.Func([IDL.Text, Entry], [], []),
    'saveReflection' : IDL.Func([IDL.Text, ReflectionData], [], []),
    'saveDailyMetrics' : IDL.Func([IDL.Text, DailyMetrics], [], []),
    'saveSettings' : IDL.Func([Settings], [], []),
  });
};

export const init = ({ IDL }) => { return []; };
