/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface StreakData {
    longest_streak: bigint;
    current_streak: bigint;
    last_reset_date?: string;
}
export interface Settings {
    streak_threshold: bigint;
}
export interface ReflectionWithDate {
    data: ReflectionData;
    date: string;
}
export interface Entry {
    ratio_bonus: bigint;
    tasks: Tasks;
    screen_time: bigint;
    note: string;
    deep_work_done: boolean;
    screen_penalty: bigint;
    final_score: bigint;
    task_score: bigint;
    productive_time: bigint;
    reflection: string;
    ratio: number;
}
export interface EntryWithDate {
    date: string;
    entry: Entry;
}
export type Tasks = Array<[string, boolean]>;
export interface ReflectionData {
    sleep_hours: number;
    energy_level: bigint;
    distraction_tags: Array<string>;
}
export interface backendInterface {
    clearAllEntries(): Promise<void>;
    clearAllReflectionData(): Promise<void>;
    getAllEntries(): Promise<Array<EntryWithDate>>;
    getAllReflectionDates(): Promise<Array<string>>;
    getAllReflections(): Promise<Array<ReflectionWithDate>>;
    getEntry(date: string): Promise<Entry | null>;
    getReflection(date: string): Promise<ReflectionData | null>;
    getSettings(): Promise<Settings>;
    getStreakData(): Promise<StreakData>;
    saveEntry(date: string, entry: Entry): Promise<void>;
    saveReflection(date: string, data: ReflectionData): Promise<void>;
    saveSettings(settings: Settings): Promise<void>;
}
import type { Entry as _Entry, ReflectionData as _ReflectionData, StreakData as _StreakData } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async clearAllEntries(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllEntries();
            return result;
        }
    }
    async clearAllReflectionData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearAllReflectionData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearAllReflectionData();
            return result;
        }
    }
    async getAllEntries(): Promise<Array<EntryWithDate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEntries();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEntries();
            return result;
        }
    }
    async getAllReflectionDates(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReflectionDates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReflectionDates();
            return result;
        }
    }
    async getAllReflections(): Promise<Array<ReflectionWithDate>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReflections();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReflections();
            return result;
        }
    }
    async getEntry(arg0: string): Promise<Entry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEntry(arg0);
                return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEntry(arg0);
            return from_candid_opt_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReflection(arg0: string): Promise<ReflectionData | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getReflection(arg0);
                return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReflection(arg0);
            return from_candid_opt_n2(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSettings(): Promise<Settings> {
        if (this.processError) {
            try {
                const result = await this.actor.getSettings();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSettings();
            return result;
        }
    }
    async getStreakData(): Promise<StreakData> {
        if (this.processError) {
            try {
                const result = await this.actor.getStreakData();
                return from_candid_StreakData_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStreakData();
            return from_candid_StreakData_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveEntry(arg0: string, arg1: Entry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEntry(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEntry(arg0, arg1);
            return result;
        }
    }
    async saveReflection(arg0: string, arg1: ReflectionData): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReflection(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReflection(arg0, arg1);
            return result;
        }
    }
    async saveSettings(arg0: Settings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveSettings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveSettings(arg0);
            return result;
        }
    }
}
function from_candid_StreakData_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StreakData): StreakData {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Entry]): Entry | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ReflectionData]): ReflectionData | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    longest_streak: bigint;
    current_streak: bigint;
    last_reset_date: [] | [string];
}): {
    longest_streak: bigint;
    current_streak: bigint;
    last_reset_date?: string;
} {
    return {
        longest_streak: value.longest_streak,
        current_streak: value.current_streak,
        last_reset_date: record_opt_to_undefined(from_candid_opt_n5(_uploadFile, _downloadFile, value.last_reset_date))
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
